language: android
sudo: false
before_install: #1.1
  - nvm install 6
  - node --version
install: #1.2
  - npm install
android: #1.3
  components:
  - build-tools-26.0.2
  - android-25
  - extra-android-m2repository
  - extra-google-google_play_services
  - extra-google-m2repository
  - addon-google_apis-google-16
cache:
  directories:
  - node_modules
script: 
#  - npm run ci #2
  - export $ANDROID_NDK=./android-ndk-r10e/
  - cd android && ./gradlew clean
  - ./gradlew assembleRelease #3
  - cd ./app/build/outputs/apk
  - ls
  - curl -F 'file=@app-internal-release-5.3.1.apk' -F 'uKey=7d42c69844b88157360fe2dc141fdf1a' -F '_api_key=be1290e71bb2fab7a9547cda2ee37d7b' 'https://www.pgyer.com/apiv1/app/upload'
